### ISSUE TITLE
Takie tam, uwagi.

### ISSUE THREAD

**Issue by KarolinaSetorek** [czyzby/bialjam17#1]
**-Pauza jest ważna.** Jak już mówiłam, gierka idealna do poczekalni w lolu na przykład.
**-odepchnięcie jest zbyt op xD serio.** To powinien być bardziej system ucieczki niż ucieknę, a przy okazji zabiję wszystko na planszy.
-co do fireballi. Licznik byłby pomocny, ale niepotrzebny, jeżeli skill castowałoby się, aż do jego całkowitego wykorzystania. Co mam na myśli? Powiedzmy, że jestem na wysokim poziomie. Mam do wykorzystania 10 kulek. Klikam przycisk, wylatuje kulka. Skill się nie zmienia, dopóki nie wykorzystam tych 10 naboi.
-**bossy po zdobyciu pewnego poziomu, stają się jak zwykłe minionki (wzrasta im życie wraz z naszym lvl)?**.
-można wprowadzić jakieś minibossy typu papierowego minionka, ale biegnącego dużo szybciej od postaci.
-czerwone kulki biją aoe? Jeżeli tak to może jakieś self destruction można wprowadzić? (Jeżeli wróg jest za blisko i się tego użyje to też się dostaje damage na twarz)
-czy zwiększenie okienka albo fullscreen są możliwe? xDD
Zależy jak bardzo chcecie tą gierkę rozwinąć. Bo akurat pomysłów mam sporo. najważniejsze są zaznaczone.

**Comment by czyzby** [comment]
1. Pod jakim przyciskiem widziałabyś pauzę?
2. Zmniejszę siłę odepchnięcia, dzięki.
3. Kilkakrotne użycie spelli miało na celu zniwelować 10s delaya - wydłużanie delaya nie ma sensu. Mogę za to dodać jakieś toasty (odseparowane od ikon na dole), które pokazują co obecnie puszczasz i ile jeszcze castów zostało.
4. W sensie - coraz silniejsze "zwykłe" potwory? Myślałem nad tym, da się zrobić.
5. Marta już robi grafikę wilka, będzie szybszy od zwykłych goblinów. I od Ciebie.
6. Można dodać obrażenia od fireballa dla postaci, to zaklęcie i tak wyszło trochę OP.
7. Nie. Gra na razie to 600x600px na sztywno, bo nie chciało mi się bawić z potencjalnymi bugami przy resize. :rofl: Mogę umożliwić rozszerzanie okna i dodać fullscreen pod F11.

Trudno powiedzieć na ile to rozwiniemy, ale mogę posiedzieć nad tym z wieczór czy dwa, żeby poprawić grywalność. Miałem pomysł na znaczne utrudnienie gry tanim kosztem (większa szansa na spawn goblinów naprzeciw Ciebie), ale na jamie nie chciałem utrudniać gry, żeby ludzie się nie zniechęcali i dało się pokazać całość na prezentacji. Możesz dopisać więcej pomysłów, najwyżej nie wszystko zrobimy.

**Comment by KarolinaSetorek** [comment]
1. pauza pod esc albo tabem.
3.pokazywanie jaki skill i ile użyć wystarczy :D 
4. Zwykłe potwory silniejsze super, Ale żeby może bossy też miały np. coraz więcej hp. Dużo więcej. Żeby poczuć że to boss
7. F11 styka. Bo grając znalazłam na pulpicie z 20 plików o których istnieniu nie miałam pojęcia xD
Ważne:
1. Mnniej ognistych kulek na poziom
2. Większe odstępy od zdobywania poziomu, więcej poziomów?
3. Może co ileś poziomów zmiana podłoża, że niby kolejne piętro? XD
