### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by hpn33** [czyzby/bialjam17#2]

**Comment by czyzby** [comment]
I usually don't revisit my game jams and hackathons projects (unless they're somehow commercially backed), and I tend to leave them in roughly the same state as I left them at the end of the competition. However, this repository is as close to a KTX game example as it gets, so I might just look into updating the dependencies and some slight refactoring. No promises, though.

**Comment by czyzby** [comment]
@hpn33 Just wanted to let you know that @jojomickymack has updated the project to a newer version of KTX - you can find it [here](https://github.com/jojomickymack/bialjam17).
